### ISSUE TITLE
use of async in useEffect

### ISSUE THREAD

**Issue by dmarcos-au** [VishalAkhouri/gapi-drive-react-ui#2]
https://github.com/VishalAkhouri/gapi-drive-react-ui/blob/8db4b9eda3887f887cbf611a22fe91f054429459/pages/index.tsx#L7

not sure if it's allowed to use async here. I believe it needs to be rewritten as 
```
  useEffect(() => {
    async () => {
      await handleClientLoad();
    }
  });
```
https://stackoverflow.com/questions/57238928/react-typescript-16-8-how-to-make-useeffect-async

**Comment by VishalAkhouri** [comment]
Thanks for reviewing. @dmarcos-au . I will update soon.

**Comment by VishalAkhouri** [comment]
@dmarcos-au yup, I missed this one. fixed along with build issue. Thanks for pointing out.

**Comment by VishalAkhouri** [comment]
@dmarcos-au yup, I missed this one. fixed along with build issue.
